<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_31</name>
   <tag></tag>
   <elementGuidId>a1dec4a8-c95b-42e1-854b-6210182adda7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='pv_id_5_panel']/div/div/table/tbody/tr[5]/td[6]/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>f1baf2d3-ce6e-4c2d-b9b5-81cd52e81754</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>p-datepicker-day</value>
      <webElementGuid>2caa94f0-561b-4278-883e-37540d9467f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>draggable</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>305e4f26-537d-4820-b626-096791812603</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>f0a3fe24-8682-4811-b0f3-97eee9f55845</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>6f56d05f-f260-4ccc-bf50-0858dc31eb74</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-pc-section</name>
      <type>Main</type>
      <value>day</value>
      <webElementGuid>f628feca-8312-442c-ad1b-bc5fcf4759c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-p-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>58dfd6ca-a05c-4909-88c6-852c6c8b667c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-p-selected</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>feffa638-c818-4fde-959c-0f70e886b865</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-pc-group-section</name>
      <type>Main</type>
      <value>tablebodycelllabel</value>
      <webElementGuid>b8746dda-7778-49dd-99c4-d466e137efb0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>cc9f1fe2-9648-49f8-9d42-367652e0e52b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>31</value>
      <webElementGuid>6abdf713-1441-4dea-9f29-72c60fecad8d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pv_id_5_panel&quot;)/div[@class=&quot;p-datepicker-calendar-container&quot;]/div[@class=&quot;p-datepicker-calendar&quot;]/table[@class=&quot;p-datepicker-day-view&quot;]/tbody[1]/tr[5]/td[@class=&quot;p-datepicker-day-cell&quot;]/span[@class=&quot;p-datepicker-day&quot;]</value>
      <webElementGuid>479f6962-a0e4-40b2-a8c3-194d47432076</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='pv_id_5_panel']/div/div/table/tbody/tr[5]/td[6]/span</value>
      <webElementGuid>368dc438-7ef9-49d2-8dd0-8b6fb6f3d695</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sa'])[1]/following::span[34]</value>
      <webElementGuid>c271a218-0e05-4565-9e97-043d934ae42b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Fr'])[1]/following::span[35]</value>
      <webElementGuid>0b4c80a1-48a0-4311-9a15-1f924acb3d66</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[5]/td[6]/span</value>
      <webElementGuid>6b05b2e3-f6ae-411d-a44e-bfb6c562af6e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = '31' or . = '31')]</value>
      <webElementGuid>994be21e-8efc-4f01-b6b3-c0763c63a3e5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
