<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Auditor_p-inputtext p-component p-filled w-full</name>
   <tag></tag>
   <elementGuidId>f78c26e1-f8a0-4363-93d0-d0ecfa97f09c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#auditor-id > input.p-inputtext.p-component.p-filled.w-full</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@value='Admin']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>5a60e348-1373-425c-887e-552f7fae8a18</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>391d1ce3-2d2e-4675-8a05-f798f30ad0ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>p-inputtext p-component p-filled w-full</value>
      <webElementGuid>5db34607-5eb5-4bcb-8d1f-863065fae1c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-pc-name</name>
      <type>Main</type>
      <value>inputtext</value>
      <webElementGuid>1c71738d-0910-41d5-b157-8fd7ddd98d66</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-pc-section</name>
      <type>Main</type>
      <value>root</value>
      <webElementGuid>43e2f41c-e541-4230-b579-5a42d843f190</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Admin</value>
      <webElementGuid>c6add38d-4faf-4ada-a3b9-993cddfeefc8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;auditor-id&quot;)/input[@class=&quot;p-inputtext p-component p-filled w-full&quot;]</value>
      <webElementGuid>3ce27c9e-e652-4e16-957f-80736715da23</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@value='Admin']</value>
      <webElementGuid>53093309-c909-4f3f-8262-8e14ad5f4e8e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='auditor-id']/input</value>
      <webElementGuid>9d299e4e-a864-4129-b873-2b8c8a5e1ff5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/span/input</value>
      <webElementGuid>03f75d4d-5fc3-4962-9276-493d1a319258</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text']</value>
      <webElementGuid>5e756b08-9998-48b1-ae3b-609a0295083f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
