<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Schedule_p-inputtext p-component p-filled w-full</name>
   <tag></tag>
   <elementGuidId>d14179ef-b3d9-4ca2-aa66-9b9668098fa5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#schedule > input.p-inputtext.p-component.p-filled.w-full</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@value='Dec 19, 2025']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>7e02f615-262b-4f18-b601-35936575553a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>6b652109-1098-4767-ba35-c6120eb78e14</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>p-inputtext p-component p-filled w-full</value>
      <webElementGuid>9fe63d80-8229-425e-83e4-74ac19b2cc54</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-pc-name</name>
      <type>Main</type>
      <value>inputtext</value>
      <webElementGuid>34c956cf-021d-4979-95f6-ab60abeaa4aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-pc-section</name>
      <type>Main</type>
      <value>root</value>
      <webElementGuid>19f60e63-5382-4ae6-bac7-7753e53a236b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Dec 19, 2025</value>
      <webElementGuid>594985a3-2b96-48fc-8721-498be47d8457</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;schedule&quot;)/input[@class=&quot;p-inputtext p-component p-filled w-full&quot;]</value>
      <webElementGuid>94f12b2a-e754-473d-bd37-c5ef1b854945</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@value='Dec 19, 2025']</value>
      <webElementGuid>94ee2e5a-61ac-477c-9398-e5c64af70dca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='schedule']/input</value>
      <webElementGuid>6cbbb08b-3069-42ba-8f76-8b906cfb9747</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/span/input</value>
      <webElementGuid>17f8a6aa-b568-4bc8-abe3-6c9c20e23179</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text']</value>
      <webElementGuid>e0d6d2e6-6e72-4b8f-953b-37fd114fa47f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
