<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_empty</name>
   <tag></tag>
   <elementGuidId>dc948644-ec2d-4b8b-95d5-73d8d76aa3eb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='pv_id_13_content']/div/div/div/span/div/div[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.p-multiselect-label-container</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>0d6871ab-8b46-4be0-9085-7048b050f7ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>p-multiselect-label-container</value>
      <webElementGuid>61e7528c-fc92-4318-9adc-9570d1a0c8cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-pc-section</name>
      <type>Main</type>
      <value>labelcontainer</value>
      <webElementGuid>36de7c20-bc71-4254-bdf7-faed3b3f95f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>empty</value>
      <webElementGuid>da9e636f-b7f9-4a43-aae5-d5dd4628057b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pv_id_13_content&quot;)/div[@class=&quot;p-panel-content&quot;]/div[@class=&quot;grid grid-cols-1 md:grid-cols-4 lg:grid-cols-4 gap-6&quot;]/div[1]/span[@class=&quot;p-floatlabel p-floatlabel-on&quot;]/div[@class=&quot;p-multiselect p-component p-inputwrapper w-full&quot;]/div[@class=&quot;p-multiselect-label-container&quot;]</value>
      <webElementGuid>d90732b6-4abb-4736-b921-77e481cb3818</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='pv_id_13_content']/div/div/div/span/div/div[2]</value>
      <webElementGuid>54e6b5f1-fb96-4fab-b907-9723a87efa6b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Filter'])[1]/following::div[8]</value>
      <webElementGuid>c21f1012-15b5-4b3a-afa0-ed0ee7a1e4c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Questioner'])[2]/following::div[12]</value>
      <webElementGuid>3249ac5d-1137-4886-b3f2-a4492c6f690b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select Departments'])[1]/preceding::div[3]</value>
      <webElementGuid>cb1352d7-20a4-4279-a9e4-6136ff7fc4cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/div/div[2]</value>
      <webElementGuid>fa031b63-4569-451d-9477-f55a33341429</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'empty' or . = 'empty')]</value>
      <webElementGuid>3ead8118-b2ed-4744-a9f0-414f4186955d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
