<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Logistik_p-checkbox p-component</name>
   <tag></tag>
   <elementGuidId>06d33532-5796-47a0-9f8a-efbacca2ec71</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='pv_id_5_3']/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#pv_id_5_3 > div.p-checkbox.p-component</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>5c9dd0db-fab8-46a4-b08f-827ab1ee9355</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>p-checkbox p-component</value>
      <webElementGuid>b845ccf1-89aa-4a50-9f43-dda3f76ad3bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-pc-name</name>
      <type>Main</type>
      <value>pcoptioncheckbox</value>
      <webElementGuid>7f59967f-2a48-4765-8555-67d90af51684</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-pc-extend</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>78b375f5-8a41-42b0-856f-8c8e088eb513</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-pc-section</name>
      <type>Main</type>
      <value>root</value>
      <webElementGuid>745f1398-3f53-4d1f-a2c1-18fbfd746c78</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-p-checked</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>81149534-6ebc-455c-8865-85c09c2200da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-p-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>24c6c703-7c77-4d41-86bc-4b8645e42833</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pv_id_5_3&quot;)/div[@class=&quot;p-checkbox p-component&quot;]</value>
      <webElementGuid>5641f311-d361-46fe-afcb-ed009d8fea8c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='pv_id_5_3']/div</value>
      <webElementGuid>14c726fc-a0a3-419c-92c7-5a5c7656445e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Logistik'])[1]/following::div[1]</value>
      <webElementGuid>33eb225a-25f0-4499-98ff-aae272fd1a20</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Laboratory'])[1]/following::div[3]</value>
      <webElementGuid>d6415a9d-75ca-421b-ac80-040183924d12</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Office'])[1]/preceding::div[2]</value>
      <webElementGuid>af2ea3c2-455b-4952-9f7c-7b061f8faefd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Warehouse'])[1]/preceding::div[4]</value>
      <webElementGuid>0ab786e8-1f7a-4bac-bce5-71d8b764faaa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[4]/div</value>
      <webElementGuid>3dd0eada-9c0d-4f80-b55d-bc34ba1e3863</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
