<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_Office</name>
   <tag></tag>
   <elementGuidId>c94eabef-a400-44ba-9870-648fd9c2fff8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='pv_id_12_3']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#pv_id_12_3</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>df62989e-e969-449f-9d2c-844d2f47dc6b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>pv_id_12_3</value>
      <webElementGuid>e285e864-ade7-4979-8f53-2368a5cf5acf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>p-multiselect-option</value>
      <webElementGuid>17598e17-d4b6-4673-a909-85548974827d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>7113b0d7-cd2d-438a-9405-72affd599207</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Office</value>
      <webElementGuid>d973d479-d12b-4721-b52e-27e07cb8a8e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>1cf76839-6822-4dd3-a0a5-5b03c801cf2f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>a201838a-ecd8-4ae7-806f-0df5d9ffa1cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-setsize</name>
      <type>Main</type>
      <value>5</value>
      <webElementGuid>10f3afd0-82d1-4173-9d45-895e84f7c007</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-posinset</name>
      <type>Main</type>
      <value>4</value>
      <webElementGuid>767d7924-c1f2-447f-adee-5f683b331f12</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-pc-section</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>715096fa-6713-46f0-b7b6-2e758e034462</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-p-selected</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>a8535c4c-cf5a-415f-90e6-d9099f40150a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-p-focused</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>7cd76aad-bd97-4401-8f41-ab63a3abe6b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-p-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>28dc7a81-8ad9-47b2-8860-8a6d2b23ac04</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Office</value>
      <webElementGuid>0fc44e89-fbe8-4910-a46b-4ff64aaa0cba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pv_id_12_3&quot;)</value>
      <webElementGuid>95645959-252a-43f9-80e6-ec4192e9f30b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//li[@id='pv_id_12_3']</value>
      <webElementGuid>4e1a0fe1-e252-478e-9c49-9fe2fff9fb05</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='pv_id_12_list']/li[4]</value>
      <webElementGuid>30f55bf6-2968-4b14-8be5-845a74ebd00f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Logistik'])[1]/following::li[1]</value>
      <webElementGuid>e3816ecd-25f5-47b3-9535-f39fb3354aac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Laboratory'])[1]/following::li[2]</value>
      <webElementGuid>e9569794-16aa-47aa-94ee-1f2280828629</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Warehouse'])[1]/preceding::li[1]</value>
      <webElementGuid>912425d8-7d55-46f2-a2cc-de8c92123e4b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/ul/li[4]</value>
      <webElementGuid>bb75e8bc-d8e8-4aa9-808e-3a39be1d3ed5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[@id = 'pv_id_12_3' and (text() = 'Office' or . = 'Office')]</value>
      <webElementGuid>7eb90b0d-7500-43cc-8ec3-689f013270fe</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
