<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Issue Admin</name>
   <tag></tag>
   <elementGuidId>fb04874c-e0cb-4923-a389-96c95be0c8fb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__nuxt']/div/div[2]/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.py-4.px-4.flex.items-center.justify-between.border-b.bg-white</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>241fba75-80b2-4f6e-b724-e9800f4017bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>py-4 px-4 flex items-center justify-between border-b bg-white</value>
      <webElementGuid>3b2ad9b7-ea1e-4ce2-9187-f9d87adb81c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Issue Admin</value>
      <webElementGuid>396189a3-e0b6-488c-9d4d-d4d54f8ef763</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__nuxt&quot;)/div[@class=&quot;bg-slate-100&quot;]/div[@class=&quot;z-0 dark:relative min-h-screen w-full overflow-x-hidden transition-all duration-300 xl:max-w-[calc(100%_-_270px)] xl:ms-[270px]&quot;]/div[@class=&quot;py-4 px-4 flex items-center justify-between border-b bg-white&quot;]</value>
      <webElementGuid>9441611c-cdbf-4e0a-a96e-04abaf58074f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__nuxt']/div/div[2]/div</value>
      <webElementGuid>00f02092-9224-4ec4-9be7-afc027b3dd4b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div</value>
      <webElementGuid>6f3f3f63-f6c6-4b2e-b2e2-7651ab56dd4d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Issue Admin' or . = 'Issue Admin')]</value>
      <webElementGuid>15c19441-ab2c-424d-8e37-3ad242170f81</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
