<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_empty_p-multiselect-dropdown</name>
   <tag></tag>
   <elementGuidId>172df9e5-3aa4-4d55-8f4c-03be19294f0a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='questioner']/div[3]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.p-multiselect-dropdown</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>ac204771-77a1-40bb-b92f-0260385c5029</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>p-multiselect-dropdown</value>
      <webElementGuid>eb3dd266-249e-45b3-a711-b61d5bb732be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-pc-section</name>
      <type>Main</type>
      <value>dropdown</value>
      <webElementGuid>86a57c9c-5689-4a7b-bce4-c8cb1d0624b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;questioner&quot;)/div[@class=&quot;p-multiselect-dropdown&quot;]</value>
      <webElementGuid>b0bd6200-1d37-4512-8519-931b53a4041c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='questioner']/div[3]</value>
      <webElementGuid>792bdcee-f39f-49fd-8218-217eebad4a7c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Filter'])[1]/following::div[10]</value>
      <webElementGuid>dc7e474a-7dd8-49bd-af46-61e702f74ac9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select Questioner'])[1]/preceding::div[1]</value>
      <webElementGuid>1ba807e9-04ba-4cbe-8221-d0c51fad496c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select Priority'])[1]/preceding::div[3]</value>
      <webElementGuid>267951ab-55f1-4bc5-94f7-cec7dddf0f04</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]</value>
      <webElementGuid>6fa63c44-2908-46b9-88d5-786104016d53</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
