<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_medium</name>
   <tag></tag>
   <elementGuidId>2c830604-1506-4020-b518-94691d59bccf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='pv_id_45_1']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#pv_id_45_1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>338801f3-4806-4404-bb64-b1c05fe5b593</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>pv_id_45_1</value>
      <webElementGuid>ce70dbdd-0c95-4b36-9f26-23d83432db81</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>p-select-option</value>
      <webElementGuid>7ecaeae8-d38e-49b4-8d03-bb0aa6d300c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>c81f1094-ea31-4265-a7f7-480513b8e794</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>medium</value>
      <webElementGuid>5c4cea80-2e41-40b2-9f64-10c57cdd2c15</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>8114e6b2-fa2b-469b-abda-4a8bf56dc4cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>68b361e5-e7f3-4c6c-846a-d594b2e4baf2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-setsize</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>6ceaa7d8-94ec-44e3-b500-b9d66d927e06</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-posinset</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>119ee73b-e4f8-4da6-be30-3aa6e8097736</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-p-selected</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>389acb3c-1a6a-474c-8aed-07165d786f50</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-p-focused</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>375dd1e7-7ec0-48ff-a478-205aef3282ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-p-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>e950b83f-0315-4c07-9fc3-9157f0821131</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-pc-section</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>50dccb83-84ae-4e72-b302-9e83744b3976</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>medium</value>
      <webElementGuid>e3343bbc-243a-4156-9ddb-10838f622d22</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pv_id_45_1&quot;)</value>
      <webElementGuid>b5456868-5c99-4063-aa40-7b167304855b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//li[@id='pv_id_45_1']</value>
      <webElementGuid>92bcab88-0d2f-4299-8ff4-3e087fd71aab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='pv_id_45_list']/li[2]</value>
      <webElementGuid>eaba2ba7-f66c-44c1-a73e-988a11fa141a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='low'])[7]/following::li[1]</value>
      <webElementGuid>48e257be-34b8-4071-9337-0b2b1e64a4f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='high'])[2]/preceding::li[1]</value>
      <webElementGuid>6d6562bf-2ade-45c1-91b2-49564e0267cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/ul/li[2]</value>
      <webElementGuid>06d05424-d065-4d1b-98c0-feff4adebf75</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[@id = 'pv_id_45_1' and (text() = 'medium' or . = 'medium')]</value>
      <webElementGuid>285060e0-69a8-4c17-922e-6fb414521da1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
