<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_No_1_2_3</name>
   <tag></tag>
   <elementGuidId>8465f1ca-9de1-4b27-82fd-6acaf13441f9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[34]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>74ed581c-f740-465a-819c-3f8849ff2cad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>0657fcbd-e813-4a73-b4ba-fd2d674e483d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>p-togglebutton p-component</value>
      <webElementGuid>2187ae0a-413e-42a8-81f5-4928cb46b637</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-pressed</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>82adcc9a-e982-4e74-92ba-051b68119e76</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-pc-name</name>
      <type>Main</type>
      <value>togglebutton</value>
      <webElementGuid>08d32946-20a5-4eeb-9750-70b2a9894a0e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-pc-section</name>
      <type>Main</type>
      <value>root</value>
      <webElementGuid>6fe841c3-9eea-4b04-8bd1-35729e7aad8d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-p-checked</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>a446db65-9c3e-442c-945e-522fb52c584b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-p-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>0b3aac30-3742-44a8-bf02-2fb34a101dd3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>No</value>
      <webElementGuid>ca494f07-2b5e-4db7-91e4-6f2be07e9906</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pv_id_40_content&quot;)/div[@class=&quot;p-panel-content&quot;]/div[@class=&quot;w-full&quot;]/div[@class=&quot;md:flex md:items-center pb-2 mb-2 border-b border-slate-200&quot;]/div[@class=&quot;md:w-2/3&quot;]/button[@class=&quot;p-togglebutton p-component&quot;]</value>
      <webElementGuid>5f0a4739-8c5e-48b3-8a8f-f7409d3650c1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[34]</value>
      <webElementGuid>f2377f38-a5e2-4f50-9703-a63737f895e5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='pv_id_40_content']/div/div/div[7]/div[2]/button</value>
      <webElementGuid>eec1ca24-0c99-4aaf-807f-8b76294f054d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Include Saturday?'])[1]/following::button[1]</value>
      <webElementGuid>2ba42d00-3d7a-4c8d-90a2-2129ab4fe0ca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Yes'])[1]/following::button[1]</value>
      <webElementGuid>0551ec8b-b1d2-42e4-929f-383e42170a95</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Include Sunday?'])[1]/preceding::button[1]</value>
      <webElementGuid>c00c542b-f2a2-44ca-9a01-f13774a0d1f3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div[7]/div[2]/button</value>
      <webElementGuid>b82f9e14-65be-4bc0-bd11-78802f9e9223</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'No' or . = 'No')]</value>
      <webElementGuid>857e0b01-5e2b-492d-b91f-0cf8cdf9ed42</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
