<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Checkin (start)_p-inputtext p-compone_02a85d_1</name>
   <tag></tag>
   <elementGuidId>d2c92878-fe9b-44ba-90a7-5f7b724171d9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@value='07:00']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input.p-inputtext.p-component.p-inputmask.p-filled.w-full</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>47ece843-d65b-4eee-83c2-9fd2877a917d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>e3c6d4e9-5f41-4a30-b259-876f636ae8d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>p-inputtext p-component p-inputmask p-filled w-full</value>
      <webElementGuid>5e85c461-538c-4883-973b-2398f96d169d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>00:00</value>
      <webElementGuid>424c7d6a-9b7c-4f35-9135-6d6ac2352c92</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-pc-section</name>
      <type>Main</type>
      <value>root</value>
      <webElementGuid>4feb1d25-48a8-48e4-9993-11ebe025e989</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-pc-name</name>
      <type>Main</type>
      <value>inputtext</value>
      <webElementGuid>91fa102a-d226-4feb-ae83-9008d178d3d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>07:00</value>
      <webElementGuid>bb724a12-1f13-423c-82ca-d3b788ef2d02</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pv_id_25_content&quot;)/div[@class=&quot;p-panel-content&quot;]/div[@class=&quot;w-full&quot;]/div[@class=&quot;md:flex md:items-center pb-2 mb-2 border-b border-slate-200&quot;]/div[@class=&quot;md:w-2/3&quot;]/input[@class=&quot;p-inputtext p-component p-inputmask p-filled w-full&quot;]</value>
      <webElementGuid>e7c20596-cba8-45bd-aeda-a78edc4c26ab</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@value='07:00']</value>
      <webElementGuid>66375a2a-f3f3-438c-8645-23870175e272</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='pv_id_25_content']/div/div/div[4]/div[2]/input</value>
      <webElementGuid>ce2dcda6-173e-408f-abbb-1a04872cb507</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input</value>
      <webElementGuid>0d4d28a7-be96-462a-9ee8-5ae1e27448bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @placeholder = '00:00']</value>
      <webElementGuid>46e7b1a0-026d-4d0e-91f1-618c7311c73c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
