<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Apply</name>
   <tag></tag>
   <elementGuidId>fdd4e0c5-c4ac-4cf1-965a-1ff4dea2d028</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.flex.justify-end.mt-4 > button.p-button.p-component</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@type='submit']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>52321b01-2e51-4806-8cfb-075305119847</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>p-button p-component</value>
      <webElementGuid>00c0406a-5398-49ea-8e94-4a7ada8a036f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>ae3e5db5-c25b-4982-abb4-29d58dcd6e11</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Apply</value>
      <webElementGuid>6c298e21-b605-490d-92ff-8cb707120ca4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-pc-name</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>337d59a6-fb9c-40ae-92f5-4fc4eb40da66</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-p-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>f12dd690-5cfb-4ca9-ae94-18ad92213946</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-pc-section</name>
      <type>Main</type>
      <value>root</value>
      <webElementGuid>3c75ae89-6d23-4bf6-97df-83cddb1dfe13</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Apply</value>
      <webElementGuid>fe1c7602-334b-4f78-bf71-7e99c225e216</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pv_id_6_content&quot;)/div[@class=&quot;p-panel-content&quot;]/div[@class=&quot;flex justify-end mt-4&quot;]/button[@class=&quot;p-button p-component&quot;]</value>
      <webElementGuid>c7039f67-0855-4ee5-adb5-5e2889989abf</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@type='submit']</value>
      <webElementGuid>3de3379a-953a-45bd-be19-5ca6a7abc98e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='pv_id_6_content']/div/div[2]/button</value>
      <webElementGuid>d23f74b7-16d4-4537-92ba-8833139dc7b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select Status'])[1]/following::button[1]</value>
      <webElementGuid>7b8376d0-95ec-4cf2-b558-53001dfb52eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Reset'])[1]/preceding::button[1]</value>
      <webElementGuid>15fe6e5b-5d45-4ecd-8a69-26c947b32aa6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div[2]/div/div[2]/button</value>
      <webElementGuid>a49b9afb-dc4a-49f2-ac65-bcd9a9fe26c4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'submit' and (text() = 'Apply' or . = 'Apply')]</value>
      <webElementGuid>6a667664-e568-4d98-890b-22dc0105611a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
