<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Search Name_p-select-dropdown</name>
   <tag></tag>
   <elementGuidId>e5637be8-9858-4ad7-abc9-9c85934df341</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.p-select-dropdown</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='pv_id_5']/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>c5b636e4-6c4b-41b2-9278-9eb0aa489f8a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>p-select-dropdown</value>
      <webElementGuid>319dcc8c-ad57-4f9a-8e6a-61e996dff024</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-pc-section</name>
      <type>Main</type>
      <value>dropdown</value>
      <webElementGuid>7e59ff0a-a924-4ba0-853c-da848c101273</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pv_id_5&quot;)/div[@class=&quot;p-select-dropdown&quot;]</value>
      <webElementGuid>157a2ec6-d50a-43bd-89e3-52c4d43911e8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='pv_id_5']/div</value>
      <webElementGuid>b61c1a1f-1e90-4247-aaa8-540ec7448d6f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Search Name'])[1]/following::div[3]</value>
      <webElementGuid>bbb7a28d-2c7b-45ea-8fab-a09400dc8cb4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Search Code'])[1]/following::div[4]</value>
      <webElementGuid>fd5beb93-8275-4d6f-aebc-907168283c1e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select Status'])[1]/preceding::div[1]</value>
      <webElementGuid>f3be2735-4d2b-477a-98cf-d385a324c32c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Apply'])[1]/preceding::div[1]</value>
      <webElementGuid>3f347188-5023-410d-a5f9-d95f29e49d60</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/div/div</value>
      <webElementGuid>679a06d0-727b-4948-9308-fbabf26147ec</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
