<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Search Code_p-inputtext p-component p_fd9f8a_1_2</name>
   <tag></tag>
   <elementGuidId>c7f40807-09a0-4e39-ac25-ce1df8ee0948</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div:nth-of-type(2) > span.p-floatlabel.p-floatlabel-on > input.p-inputtext.p-component.p-filled.w-full</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@value='ware']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ea59a1b0-2265-41e1-b936-da762a109b2d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>99098fdc-15ac-454a-90c2-271203de8ad2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>p-inputtext p-component p-filled w-full</value>
      <webElementGuid>dc99a637-c9d4-4275-b044-f1c7aeb18352</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-pc-name</name>
      <type>Main</type>
      <value>inputtext</value>
      <webElementGuid>be039a2f-80da-46dd-919c-b86fc2a42e43</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-pc-section</name>
      <type>Main</type>
      <value>root</value>
      <webElementGuid>ddc4b1af-75f3-4645-9762-da1c7993fb1f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>ware</value>
      <webElementGuid>bfaeb2e3-fde6-4085-b628-6098e62cc42e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pv_id_14_content&quot;)/div[@class=&quot;p-panel-content&quot;]/div[@class=&quot;grid grid-cols-1 md:grid-cols-3 lg:grid-cols-3 gap-6&quot;]/div[2]/span[@class=&quot;p-floatlabel p-floatlabel-on&quot;]/input[@class=&quot;p-inputtext p-component p-filled w-full&quot;]</value>
      <webElementGuid>d2dc2f7d-3ca7-4c2b-8596-bff67a47c775</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@value='ware']</value>
      <webElementGuid>1512c747-8c81-477f-b25b-17ea022ad161</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='pv_id_14_content']/div/div/div[2]/span/input</value>
      <webElementGuid>e84857e8-4f9a-49ad-a94b-d475a7b55046</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/span/input</value>
      <webElementGuid>22599023-c675-4421-aba9-fd9085817cf3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text']</value>
      <webElementGuid>cf7e8439-c8a2-4a64-97bc-9f6fedc871ec</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
