<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Select Location</name>
   <tag></tag>
   <elementGuidId>91cac4dd-97ac-463a-a93b-488bc2fa043d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='location']/div[2]/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.p-multiselect-label.p-placeholder</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>075396b4-6a4a-4816-a65e-d072e8762f9f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>p-multiselect-label p-placeholder</value>
      <webElementGuid>c9f691a7-f2b9-4dac-97c1-5048f1230d27</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-pc-section</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>4af00bf0-ee15-44e9-97a6-72dce6cda183</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Select Location</value>
      <webElementGuid>7e364d39-3e94-484b-a02d-52d7e9731d61</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;location&quot;)/div[@class=&quot;p-multiselect-label-container&quot;]/div[@class=&quot;p-multiselect-label p-placeholder&quot;]</value>
      <webElementGuid>67cc3be1-c780-4c20-b5b2-97a047ef50e3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='location']/div[2]/div</value>
      <webElementGuid>435234ff-1ea4-4a09-92eb-1d57d3ca327d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Location'])[1]/following::div[4]</value>
      <webElementGuid>ff7a46bc-789c-46ad-811e-6764a33642a8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Schedule Period'])[1]/preceding::div[2]</value>
      <webElementGuid>55ccbff2-c167-468d-a038-7f089e073a80</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Apply'])[1]/preceding::div[4]</value>
      <webElementGuid>af9d8658-5005-47ac-8dea-7d5fa1b645b5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Select Location']/parent::*</value>
      <webElementGuid>a215b564-4167-4407-a99c-353eaad020e2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div[2]/div</value>
      <webElementGuid>f0ae376c-1754-4535-af2d-d74d55439a59</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Select Location' or . = 'Select Location')]</value>
      <webElementGuid>8808cdf4-47cd-4104-af39-c11b3522c688</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
