<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_WIB 7</name>
   <tag></tag>
   <elementGuidId>fe7b95ea-d291-4c28-93cb-82fd16aed801</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='pv_id_20_0']/div/div[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.text-slate-500</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>61034ceb-0a0b-401e-b52a-dc83708d6709</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-slate-500</value>
      <webElementGuid>73fca45c-d5d7-46ec-89f6-1b772a9dcae8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>WIB +7</value>
      <webElementGuid>83e7e1b6-d779-4828-8670-eec894084293</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pv_id_20_0&quot;)/div[1]/div[@class=&quot;text-slate-500&quot;]</value>
      <webElementGuid>0eddbfed-fdce-4d70-b964-13495d1ff242</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='pv_id_20_0']/div/div[2]</value>
      <webElementGuid>5accee28-6643-4bfd-a9a4-7c461445b5fc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Asia/Jakarta'])[1]/following::div[1]</value>
      <webElementGuid>117716c1-8c28-466d-83b9-86ddb5ea7a24</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Save'])[1]/following::div[5]</value>
      <webElementGuid>48bed3ed-d7da-4694-876c-1a1ae1801d4d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Asia/Jayapura'])[1]/preceding::div[1]</value>
      <webElementGuid>59094b4f-9be4-4b9d-a35d-42d838194a89</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='WIT +9'])[1]/preceding::div[2]</value>
      <webElementGuid>b9d31179-e274-4e82-8e13-6183df25ace8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='WIB +7']/parent::*</value>
      <webElementGuid>ec1244c6-059c-457a-98a7-f6d720c72b89</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/div/div[2]</value>
      <webElementGuid>af5cdaba-edd3-449f-99e2-687cfe51f8b4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'WIB +7' or . = 'WIB +7')]</value>
      <webElementGuid>5260bd4e-4109-465f-931d-a88076e14c50</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
