<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Department_p-select-dropdown</name>
   <tag></tag>
   <elementGuidId>989b2639-98f2-4a7f-a1bb-80cd6a41a3ce</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='pv_id_11']/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#pv_id_11 > div.p-select-dropdown</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>f37bb05e-9f3d-48b2-989a-7f65543171b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>p-select-dropdown</value>
      <webElementGuid>c2418ad3-3e59-43b0-b4b9-33cc75c7e9ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-pc-section</name>
      <type>Main</type>
      <value>dropdown</value>
      <webElementGuid>0ca05861-36a7-47b1-bc1b-a164108a695e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pv_id_11&quot;)/div[@class=&quot;p-select-dropdown&quot;]</value>
      <webElementGuid>11a56437-535d-4c2d-923f-604fee4894c9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='pv_id_11']/div</value>
      <webElementGuid>ba8f3398-1859-4b57-8371-4e5d244eb099</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Department'])[3]/following::div[3]</value>
      <webElementGuid>a8fc025a-2eb1-4db9-a208-eee14a80a7ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Add Location'])[1]/following::div[8]</value>
      <webElementGuid>43d15827-0adc-4d37-8492-e68933eb18b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Code'])[2]/preceding::div[1]</value>
      <webElementGuid>266e0b70-b4c3-4d9b-b0af-e298acf0b69a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Name'])[2]/preceding::div[4]</value>
      <webElementGuid>8c5f01cf-4331-400d-b2fa-308098fe5218</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/div/div[2]/div/div</value>
      <webElementGuid>53ff53eb-8018-4ef0-8fef-9a03149b83ee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='pv_id_19']/div</value>
      <webElementGuid>22aa7f4a-853b-45a1-80fe-7fb4b8dc8927</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
