<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_WIB 7</name>
   <tag></tag>
   <elementGuidId>fe7b95ea-d291-4c28-93cb-82fd16aed801</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//span[normalize-space()='Asia/Jakarta'])[1]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.text-slate-500</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>90757a9d-8d65-4b18-bfcc-172e6adc6c92</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-slate-500</value>
      <webElementGuid>ee608597-0567-4699-87f6-1b66c2bb26d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>WIB +7</value>
      <webElementGuid>ebdb27f4-ebeb-4cfb-ae3f-2258c9467842</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pv_id_20_0&quot;)/div[1]/div[@class=&quot;text-slate-500&quot;]</value>
      <webElementGuid>37b9c713-a458-4b2a-b052-94aaa7b63304</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='pv_id_20_0']/div/div[2]</value>
      <webElementGuid>745cd88f-b43e-44c1-bd95-aad103a88c7e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Asia/Jakarta'])[1]/following::div[1]</value>
      <webElementGuid>6bef1d77-04f7-4a07-91cd-9088bbc8db37</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Save'])[1]/following::div[5]</value>
      <webElementGuid>cb6719ff-9451-487a-9ea4-86ee43271722</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Asia/Jayapura'])[1]/preceding::div[1]</value>
      <webElementGuid>9b345606-08d6-421c-9f57-e660947bcad7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='WIT +9'])[1]/preceding::div[2]</value>
      <webElementGuid>9fbf4232-5feb-45ed-a802-2ddd8d664046</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='WIB +7']/parent::*</value>
      <webElementGuid>f65f08e5-d722-4ef6-bba4-93e978d2e096</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/div/div[2]</value>
      <webElementGuid>2154471e-e112-4d55-824b-e7e46a3a0c80</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'WIB +7' or . = 'WIB +7')]</value>
      <webElementGuid>97d61c09-a02d-43ec-ac21-c53fbb49b417</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
