<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Select Departments_p-inputtext p-comp_e30206_1_2_3_4</name>
   <tag></tag>
   <elementGuidId>009312bd-55e6-42b9-8b61-f748d0699af8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@value='offic']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input.p-inputtext.p-component.p-filled.w-full</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b9f670d7-a60c-447c-9da3-2d514512904f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>2a076d94-3c3b-4517-9d83-22d9217f130c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>p-inputtext p-component p-filled w-full</value>
      <webElementGuid>291cb5c6-0ce3-4e82-976f-4f94afb4dd1a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-pc-name</name>
      <type>Main</type>
      <value>inputtext</value>
      <webElementGuid>3f947977-8555-420d-aec3-17427bd73540</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-pc-section</name>
      <type>Main</type>
      <value>root</value>
      <webElementGuid>7ed33076-32c4-42ec-959f-47fcd10e347e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>offic</value>
      <webElementGuid>8ef1efe5-ed83-43f8-87ac-2464568d08a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pv_id_6_content&quot;)/div[@class=&quot;p-panel-content&quot;]/div[@class=&quot;grid grid-cols-1 md:grid-cols-3 lg:grid-cols-3 gap-6&quot;]/div[2]/span[@class=&quot;p-floatlabel p-floatlabel-on&quot;]/input[@class=&quot;p-inputtext p-component p-filled w-full&quot;]</value>
      <webElementGuid>d085f090-648a-4878-8c02-6295cc8bfcab</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@value='offic']</value>
      <webElementGuid>752ed1e5-1590-4e4a-bdf3-fc1d2fa94fe6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='pv_id_6_content']/div/div/div[2]/span/input</value>
      <webElementGuid>0eb83bfe-048a-48b4-b3e7-41d005cb6531</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/input</value>
      <webElementGuid>f0cedfe7-f053-4a81-bc23-6429a9d10530</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text']</value>
      <webElementGuid>e7e5f734-fba4-4513-92ce-09fda8ffb40a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
