<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Description_p-inputtext p-component p_5fc144_1_2_3_4_5_6_7_8</name>
   <tag></tag>
   <elementGuidId>de3ed330-422e-45c0-afbd-bb67b4cc2227</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@value='TestKatal']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c804f842-4f1f-4f4b-a552-26e24ad0c164</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>0f3fa640-afe8-4ead-8e2a-697aa2fd989a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>p-inputtext p-component p-filled w-full</value>
      <webElementGuid>a88ab91a-3bc2-48db-ab3f-2cb7aa6c45c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-pc-name</name>
      <type>Main</type>
      <value>inputtext</value>
      <webElementGuid>808130e9-d92a-4b72-ba1b-b558537525dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-pc-section</name>
      <type>Main</type>
      <value>root</value>
      <webElementGuid>5886beca-9a1e-45dd-a6aa-5d2326622a7a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>TestKatal</value>
      <webElementGuid>364289d1-e3e3-40e5-b028-d5a7dfa235af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;light-mode&quot;]/body[1]/div[@class=&quot;p-drawer-mask p-overlay-mask p-overlay-mask-enter p-drawer-open p-drawer-right&quot;]/div[@class=&quot;p-drawer p-component&quot;]/div[@class=&quot;p-drawer-content&quot;]/div[1]/form[1]/div[@class=&quot;w-full&quot;]/div[@class=&quot;md:flex md:items-center pb-2 mb-2 border-b border-slate-200&quot;]/div[@class=&quot;md:w-2/3&quot;]/input[@class=&quot;p-inputtext p-component p-filled w-full&quot;]</value>
      <webElementGuid>211bdf71-0c6c-47bb-9ca8-84adc0ce44c5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@value='TestKatal']</value>
      <webElementGuid>e103880d-b279-4e6f-8cee-44b9b7bab4ed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div[2]/input</value>
      <webElementGuid>90573685-6ad3-49ab-aca2-2da4cf3acaad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text']</value>
      <webElementGuid>7e9ce21b-12d7-4c36-b73d-3f148a2e5807</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
