<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Search Code_p-inputtext p-component p_fd9f8a_1_2_3</name>
   <tag></tag>
   <elementGuidId>67b2aada-5cfd-40f7-a1b8-86b6a31f3ffd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@value='info']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div:nth-of-type(3) > span.p-floatlabel.p-floatlabel-on > input.p-inputtext.p-component.p-filled.w-full</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b2011ea8-4cf5-4db1-b48f-64632849d140</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>3e663255-dfef-4521-9841-a758ae1674ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>p-inputtext p-component p-filled w-full</value>
      <webElementGuid>0679409c-87bc-4b24-9a70-f1b651d71afc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-pc-name</name>
      <type>Main</type>
      <value>inputtext</value>
      <webElementGuid>dad4d7f7-9090-458b-ba26-6ba9f18d2d2e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-pc-section</name>
      <type>Main</type>
      <value>root</value>
      <webElementGuid>c5749af2-9794-465a-9ea6-5af7d69be12d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>info</value>
      <webElementGuid>4048ea62-e378-425f-83a5-6f06a781be9f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pv_id_6_content&quot;)/div[@class=&quot;p-panel-content&quot;]/div[@class=&quot;grid grid-cols-1 md:grid-cols-3 lg:grid-cols-3 gap-6&quot;]/div[3]/span[@class=&quot;p-floatlabel p-floatlabel-on&quot;]/input[@class=&quot;p-inputtext p-component p-filled w-full&quot;]</value>
      <webElementGuid>ec875497-b9a7-4768-96c6-f30cdcde099f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@value='info']</value>
      <webElementGuid>26268a73-28a1-499f-84c4-5c995dea13f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='pv_id_6_content']/div/div/div[3]/span/input</value>
      <webElementGuid>007e29f7-35ae-4983-bdbf-fe9dd4f2efaa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/span/input</value>
      <webElementGuid>2c3d17ce-21f7-41f4-8f81-d45c70c9718c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text']</value>
      <webElementGuid>25f34bcf-7209-41ca-b259-08e1526231f3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
