<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_Office (1)</name>
   <tag></tag>
   <elementGuidId>41e22c78-05f7-4ed6-bf7f-516637816201</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#pv_id_5_3</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='pv_id_5_3']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>49cfb9c7-7d2c-4220-9ca0-c6a6b4fd41e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>pv_id_5_3</value>
      <webElementGuid>ae49e06a-23df-48cc-b0fb-c0d11638eed5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>p-multiselect-option p-focus</value>
      <webElementGuid>d70e5573-90b1-4d9c-8902-06c84e135407</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>410db955-1ac9-4d14-8821-9af5e77477f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Office</value>
      <webElementGuid>018e4fdb-5e8b-4afe-8fd5-69dc961b7185</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>72eb299c-63d1-4256-8fcd-61464d13ee5e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>aaeb8d32-0093-475a-9e88-73ed17461a97</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-setsize</name>
      <type>Main</type>
      <value>5</value>
      <webElementGuid>3ac16fb1-902f-45e7-9fda-b07cfa8ac9cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-posinset</name>
      <type>Main</type>
      <value>4</value>
      <webElementGuid>5b8e0f52-bbe8-4c7d-868c-4ab5e05cfd6a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-pc-section</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>419699b4-119d-4be5-ac0d-28a6ca0d4fcf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-p-selected</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>d0f503f2-903d-4acf-a550-89a792e64a54</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-p-focused</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>269b2fb1-dbb5-4f8f-8596-e29d9d58677a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-p-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>dd1fe43f-e522-4ef4-a5c9-e00fd4df1bde</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Office</value>
      <webElementGuid>b3261481-a0b0-437d-8613-559b6c73967f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pv_id_5_3&quot;)</value>
      <webElementGuid>b5e5f4ac-8944-4539-8fe0-106d60b25604</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//li[@id='pv_id_5_3']</value>
      <webElementGuid>ed75defb-daa8-4937-a5ac-76f53d13085b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='pv_id_5_list']/li[4]</value>
      <webElementGuid>6a3ef9fc-f683-4566-b9ae-307e4ea5c24a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Logistik'])[1]/following::li[1]</value>
      <webElementGuid>7bbcdb52-864e-4f54-917a-8f5404fc0c5c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Laboratory'])[1]/following::li[2]</value>
      <webElementGuid>1e2b5258-5abb-4201-b8d6-e20458066bc4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Warehouse'])[1]/preceding::li[1]</value>
      <webElementGuid>20d473d6-f3bf-4f3b-964e-2bfb08324fc8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/ul/li[4]</value>
      <webElementGuid>e9073aab-9b96-48a9-9acc-bf3e72de7d8f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[@id = 'pv_id_5_3' and (text() = 'Office' or . = 'Office')]</value>
      <webElementGuid>3584aef8-c819-4278-beae-30ae8f662c81</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
