<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_</name>
   <tag></tag>
   <elementGuidId>250818b0-73bc-4a40-906f-7109e8775d31</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.p-panel-header-actions > #pv_id_7_header</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='pv_id_7_header']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>3df1d808-61ed-42ba-8b70-795fc2c5732b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>p-button p-component p-button-icon-only p-button-secondary p-button-rounded p-button-text p-panel-toggle-button</value>
      <webElementGuid>810ab0e2-9890-43e2-9759-7e0d5221bd51</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>1892563d-85a8-408a-8bce-a05fb7afda1c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Filter</value>
      <webElementGuid>1b22b141-e9f0-4649-9ae2-2bf5a8c5a066</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-pc-name</name>
      <type>Main</type>
      <value>pctogglebutton</value>
      <webElementGuid>b6b3c0f1-e01a-4012-b781-79ae0386614d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-p-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>ff29a3ee-aea3-4b0b-806b-82ca3d0c141c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-p-severity</name>
      <type>Main</type>
      <value>secondary</value>
      <webElementGuid>22bbe0e5-7092-4bc0-b74e-804744aeb4b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>pv_id_7_header</value>
      <webElementGuid>20863d94-d874-493a-991e-437836a3973f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>pv_id_7_content</value>
      <webElementGuid>647c0d45-502b-402d-9002-d025b3c64d6e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>7f41edea-2809-41cf-b009-854e2a1dc3e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-pc-extend</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>61dc10a5-3591-4f4c-b595-4fe63830b010</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-pc-section</name>
      <type>Main</type>
      <value>root</value>
      <webElementGuid>ec016721-ccff-45c7-bbd1-37b7528c01e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> </value>
      <webElementGuid>14649b3d-15d8-496b-8f3e-1ad1f063fc26</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__nuxt&quot;)/div[@class=&quot;bg-slate-100&quot;]/div[@class=&quot;z-0 dark:relative min-h-screen w-full overflow-x-hidden transition-all duration-300 xl:max-w-[calc(100%_-_270px)] xl:ms-[270px]&quot;]/div[@class=&quot;mx-auto w-full mt-0&quot;]/main[1]/div[1]/div[@class=&quot;w-full md:w-[calc(100%)] bg-slate-100 transition-all&quot;]/div[@class=&quot;p-4&quot;]/div[@class=&quot;grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6 mb-6&quot;]/div[@class=&quot;col-span-3 md:col-span-3 bg-white p-6 rounded-md border border-gray-100 shadow-md shadow-black/5 mb-6&quot;]/div[@class=&quot;p-panel p-component p-panel-toggleable&quot;]/div[@class=&quot;p-panel-header&quot;]/div[@class=&quot;p-panel-header-actions&quot;]/button[@id=&quot;pv_id_7_header&quot;]</value>
      <webElementGuid>546e5886-7ca9-4cff-a372-28f4eaa95cd8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='pv_id_7_header']</value>
      <webElementGuid>7c2d9385-b3f3-460a-bf43-f4f966ca8ffb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__nuxt']/div/div[2]/div[2]/main/div/div/div/div/div/div/div/div/button</value>
      <webElementGuid>ceb8d471-32b2-45a1-9894-40d3cb9dadfc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Filter'])[1]/following::button[1]</value>
      <webElementGuid>c3250960-fbe0-452c-b295-cf608d177652</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Admin'])[1]/following::button[1]</value>
      <webElementGuid>21bb6e8c-f0fe-40b4-9e80-49d25be5c043</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Department'])[1]/preceding::button[1]</value>
      <webElementGuid>589c119c-a12a-41d1-bd74-62eff51960f3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div/div/div/button</value>
      <webElementGuid>7d0eb6b5-1a38-42d8-b6cd-13950e2c3c86</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @id = 'pv_id_7_header' and (text() = ' ' or . = ' ')]</value>
      <webElementGuid>69a5360b-b98b-4a64-af04-d7c1215ca966</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
