<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Select Schedule Type_p-select-dropdown</name>
   <tag></tag>
   <elementGuidId>86eee6f3-8106-4c91-a50c-038a5923a908</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.p-select-dropdown</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='pv_id_5']/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>f913214e-20b6-4c42-a59e-7b75368d96d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>p-select-dropdown</value>
      <webElementGuid>e5fecb84-a5f3-4302-88fa-d75052ada3e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-pc-section</name>
      <type>Main</type>
      <value>dropdown</value>
      <webElementGuid>90900627-a035-48df-afa6-967e1d445df3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pv_id_5&quot;)/div[@class=&quot;p-select-dropdown&quot;]</value>
      <webElementGuid>163e0a8a-724a-4def-8bdb-bded29a110ad</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='pv_id_5']/div</value>
      <webElementGuid>0baf64e6-67cd-4727-9837-81889fabab5f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Schedule Type'])[1]/following::div[2]</value>
      <webElementGuid>6550d2ff-0310-4711-ab7a-da000df9838e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Schedule Period'])[1]/preceding::div[1]</value>
      <webElementGuid>8ad0aeea-de89-4aee-a750-9eee67f5313c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Apply'])[1]/preceding::div[2]</value>
      <webElementGuid>834ed634-3f1e-404a-95ec-57f8d3f13ffc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div</value>
      <webElementGuid>7cdf2ec7-580e-4182-a860-d3ce8d1c5a0a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
