<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Select Departments_p-multiselect-dropdown</name>
   <tag></tag>
   <elementGuidId>ede15ff5-f359-4696-90b9-4ac49b2b8280</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;department&quot;)/div[@class=&quot;p-multiselect-dropdown&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//label[normalize-space()='Department']/following::input[1]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.p-multiselect-dropdown</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>c5960c50-9b55-43b2-879d-3b62e52a3405</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>p-multiselect-dropdown</value>
      <webElementGuid>5e28544e-1083-4dd1-b1ac-1f84addb4f46</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-pc-section</name>
      <type>Main</type>
      <value>dropdown</value>
      <webElementGuid>d4515e50-e0b8-4d8d-95b0-00377629c419</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;department&quot;)/div[@class=&quot;p-multiselect-dropdown&quot;]</value>
      <webElementGuid>084d70bf-13c8-4de5-9255-7f3ba9ea7f00</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='department']/div[3]</value>
      <webElementGuid>87da99b8-cc48-4338-ba83-e500cfb602be</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Department'])[1]/following::div[5]</value>
      <webElementGuid>0437dff8-e27b-4f85-83d5-ee531f998586</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Auditor'])[1]/preceding::div[1]</value>
      <webElementGuid>6e9e1da0-51e1-4d01-943d-d3a558fc673b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]</value>
      <webElementGuid>fb72a663-2057-48f2-b8e5-78df50ce862a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
