<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_empty_p-multiselect-dropdown_1</name>
   <tag></tag>
   <elementGuidId>89624995-4789-4f42-8256-ca6145989c52</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='pv_id_9_content']/div/div/div[3]/span/div/div[3]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div:nth-of-type(3) > span.p-floatlabel.p-floatlabel-on > div.p-multiselect.p-component.p-inputwrapper.p-multiselect-display-chip.w-full > div.p-multiselect-dropdown</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>f485f9a5-0543-456d-9a0d-62ffcb749b18</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>p-multiselect-dropdown</value>
      <webElementGuid>7031f4b0-8fb4-4c62-ad52-a499217a12c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-pc-section</name>
      <type>Main</type>
      <value>dropdown</value>
      <webElementGuid>d1943e7f-0df1-449d-bdc7-31ce9e380cc6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pv_id_9_content&quot;)/div[@class=&quot;p-panel-content&quot;]/div[@class=&quot;grid grid-cols-1 md:grid-cols-4 lg:grid-cols-4 gap-6&quot;]/div[3]/span[@class=&quot;p-floatlabel p-floatlabel-on&quot;]/div[@class=&quot;p-multiselect p-component p-inputwrapper p-multiselect-display-chip w-full&quot;]/div[@class=&quot;p-multiselect-dropdown&quot;]</value>
      <webElementGuid>7a6227ab-ef3d-416f-acd7-0c6fcf37cfb7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='pv_id_9_content']/div/div/div[3]/span/div/div[3]</value>
      <webElementGuid>185bfced-8c01-4db9-bb44-a398b04b2468</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select Schedule Type'])[1]/following::div[6]</value>
      <webElementGuid>76fd4e0a-ef87-4cc0-895f-90bae4c98d06</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select Location'])[1]/preceding::div[1]</value>
      <webElementGuid>8fa9f11f-c14c-4cc9-8639-2af5e4e0a056</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/span/div/div[3]</value>
      <webElementGuid>f36f1e59-f000-463c-abf3-aca78b549c5c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='pv_id_105_content']/div/div/div[3]/span/div/div[3]</value>
      <webElementGuid>6a432247-8272-43c3-9261-1b5d99aaad35</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
