<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_empty_p-multiselect-dropdown_1_2</name>
   <tag></tag>
   <elementGuidId>4bca3619-d5f2-4bd6-93a1-d0d7ba968603</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='pv_id_9_content']/div/div/div[4]/span/div/div[3]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div:nth-of-type(4) > span.p-floatlabel.p-floatlabel-on > div.p-multiselect.p-component.p-inputwrapper.p-multiselect-display-chip.w-full > div.p-multiselect-dropdown</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>8df39485-b354-4ef1-ac0a-446788d8db4b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>p-multiselect-dropdown</value>
      <webElementGuid>418e2c65-dc27-4f86-a4ee-11f8b554cadc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-pc-section</name>
      <type>Main</type>
      <value>dropdown</value>
      <webElementGuid>422828b7-4309-4e2b-b4aa-b7a27d84740f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pv_id_9_content&quot;)/div[@class=&quot;p-panel-content&quot;]/div[@class=&quot;grid grid-cols-1 md:grid-cols-4 lg:grid-cols-4 gap-6&quot;]/div[4]/span[@class=&quot;p-floatlabel p-floatlabel-on&quot;]/div[@class=&quot;p-multiselect p-component p-inputwrapper p-multiselect-display-chip w-full&quot;]/div[@class=&quot;p-multiselect-dropdown&quot;]</value>
      <webElementGuid>2a75f379-b4f1-4dd8-9d83-a36a575b05f0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='pv_id_9_content']/div/div/div[4]/span/div/div[3]</value>
      <webElementGuid>695ff493-8dd4-4f9d-8f07-c1e18f90b519</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select Location'])[1]/following::div[6]</value>
      <webElementGuid>ebc1eddc-26ee-4b75-8f6f-6621bc92efa5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select Auditors'])[1]/preceding::div[1]</value>
      <webElementGuid>4651413d-f6f0-4487-b961-c0d621e02ab9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Period'])[1]/preceding::div[1]</value>
      <webElementGuid>23a6aa9d-73ce-4792-9cc1-65973b419312</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/span/div/div[3]</value>
      <webElementGuid>539163da-df0c-4e87-a04e-db484c0095f1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='pv_id_105_content']/div/div/div[4]/span/div/div[3]</value>
      <webElementGuid>74444bf4-49d4-4083-b5b8-816f9593b7ac</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
