<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Reason Missed_p-inputtext p-component_8f50d1</name>
   <tag></tag>
   <elementGuidId>111fe371-769e-4b4a-a18c-78edf7526f60</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@value='T']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input.p-inputtext.p-component.p-filled.w-full</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>49ec0749-96b2-410a-b6b4-7c9a0fcd1491</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>7e5a3f30-3265-4b34-bf9c-716a891d5eb1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>p-inputtext p-component p-filled w-full</value>
      <webElementGuid>0059b723-9e19-4970-98a6-fea090ace5b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-pc-name</name>
      <type>Main</type>
      <value>inputtext</value>
      <webElementGuid>c3182bea-17f1-4d37-90cb-e13d918580aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-pc-section</name>
      <type>Main</type>
      <value>root</value>
      <webElementGuid>9589275a-4e06-49eb-b013-9df2de40b665</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>T</value>
      <webElementGuid>9fe78d50-aca7-44da-ac6b-4ad7b583d5ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;light-mode&quot;]/body[1]/div[@class=&quot;p-drawer-mask p-overlay-mask p-overlay-mask-enter p-drawer-open p-drawer-right&quot;]/div[@class=&quot;p-drawer p-component&quot;]/div[@class=&quot;p-drawer-content&quot;]/div[1]/form[1]/div[@class=&quot;w-full&quot;]/div[@class=&quot;md:flex md:items-center pb-2 mb-2 border-b border-slate-200&quot;]/div[@class=&quot;md:w-2/3&quot;]/input[@class=&quot;p-inputtext p-component p-filled w-full&quot;]</value>
      <webElementGuid>90ce8635-5d32-4667-abf3-c6afd427df82</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@value='T']</value>
      <webElementGuid>3e393960-735e-4648-a84f-5a746eb3a9c5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input</value>
      <webElementGuid>ba47bba8-f0c0-4ed2-a22b-62f4b518c301</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text']</value>
      <webElementGuid>8f1ec530-c365-4b03-81be-66fba7bff37f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
