<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button__1</name>
   <tag></tag>
   <elementGuidId>c332f256-2f07-4c08-83f9-bd6018ef377d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='pv_id_13_header']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#pv_id_13_header</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>11d7a965-ea43-4751-9365-af630f44943b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>p-button p-component p-button-icon-only p-button-secondary p-button-rounded p-button-text p-panel-toggle-button</value>
      <webElementGuid>b228d7d9-5980-46bf-a4ab-26eecad33e0a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>0cc2e83f-a532-46db-a8d9-da02616688eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-pc-name</name>
      <type>Main</type>
      <value>pctogglebutton</value>
      <webElementGuid>4cb471a2-19d5-4963-8c9c-11eb6117b3db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-p-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>c46ac997-e586-43ca-b4b7-f00228f5226e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-p-severity</name>
      <type>Main</type>
      <value>secondary</value>
      <webElementGuid>d2483057-60fc-409b-aae7-7519bcd5e636</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>pv_id_13_header</value>
      <webElementGuid>4321acc6-1a5c-41f9-99c4-a3278b09bb1b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>pv_id_13_content</value>
      <webElementGuid>7ca71db0-3a46-4b44-ae5f-9cdb9b6aabca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>b6470899-834f-419c-8ead-44125c3753b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-pc-extend</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>ed9d2796-eb1a-41b0-aebe-242e6f6295f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-pc-section</name>
      <type>Main</type>
      <value>root</value>
      <webElementGuid>aea96d16-8539-47b0-8572-8be9d2ab0196</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> </value>
      <webElementGuid>bdae7d30-77d4-4daf-b509-72da4081ddc7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pv_id_13_header&quot;)</value>
      <webElementGuid>5a7413a2-0abe-477a-9462-a658b96e1a33</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='pv_id_13_header']</value>
      <webElementGuid>12882474-9c2c-4813-81fb-812dc5f66255</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__nuxt']/div/div[2]/div[2]/main/div[2]/div/div/div[2]/div/div/div[2]/button[3]</value>
      <webElementGuid>5b2e435e-9c89-49af-8dba-8e92ee58aba4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Add Category'])[1]/following::button[3]</value>
      <webElementGuid>31f402f3-80f8-46e9-9ee6-b3f36cca942a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Description'])[1]/following::button[4]</value>
      <webElementGuid>7325e5f8-4f4c-4d8d-8fd0-84d14582dc53</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Selection Answer'])[1]/preceding::button[3]</value>
      <webElementGuid>a14791f3-397d-4ce2-b708-b699311cebed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div[2]/button[3]</value>
      <webElementGuid>26abb3c3-3866-4360-8749-4aaa8128e180</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @id = 'pv_id_13_header' and (text() = ' ' or . = ' ')]</value>
      <webElementGuid>07b9732e-7d2a-41fc-8a58-0d155f29ad2b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
