<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Green_p-select-dropdown_1</name>
   <tag></tag>
   <elementGuidId>03ed295c-a181-42a6-b9fe-aad36cfd7869</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[@class = 'p-select-dropdown' and @data-pc-section = 'dropdown']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#pv_id_43 > div.p-select-dropdown</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//span[normalize-space()='Green'])[6]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>104fc6eb-4343-48d2-bb4e-a0675f9ed978</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>p-select-dropdown</value>
      <webElementGuid>5dd24519-c3cb-47eb-aa93-96be9db071ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-pc-section</name>
      <type>Main</type>
      <value>dropdown</value>
      <webElementGuid>0ff4fd18-cfac-4601-8528-b33c70631dd9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pv_id_43&quot;)/div[@class=&quot;p-select-dropdown&quot;]</value>
      <webElementGuid>0e076b6a-3da0-44cf-b021-1133bc0a0da5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='pv_id_43']/div</value>
      <webElementGuid>2b4a2f17-6950-46d7-9725-8563c9f03d04</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Add Option'])[1]/preceding::div[1]</value>
      <webElementGuid>8ceee356-14f8-4163-a699-0d4fb37aec88</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Photo Attachment'])[2]/preceding::div[1]</value>
      <webElementGuid>49117eb4-c8c2-4e80-8edd-f0d39fea5a5a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div</value>
      <webElementGuid>1f8b131e-548f-4607-844c-fdc19f06ce29</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='pv_id_31']/div</value>
      <webElementGuid>fd72f530-f353-4ae5-8230-dc257f67d642</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
