<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Green_p-select-dropdown</name>
   <tag></tag>
   <elementGuidId>e9a0a163-4ffa-4481-aea1-e2054d28c8d7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='pv_id_29']/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#pv_id_29 > div.p-select-dropdown</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>811a8177-3a5c-4354-9927-30baf052a83d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>p-select-dropdown</value>
      <webElementGuid>3170fbc6-e92c-47c0-91d3-9bf0dbae527d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-pc-section</name>
      <type>Main</type>
      <value>dropdown</value>
      <webElementGuid>8c79af1d-0f60-44ee-80e8-5fc371555de0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pv_id_29&quot;)/div[@class=&quot;p-select-dropdown&quot;]</value>
      <webElementGuid>586dddb6-a57a-49c0-8125-e0b5db93313f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='pv_id_29']/div</value>
      <webElementGuid>764631df-4668-4a55-9d11-c7e214ffdeca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Add Option'])[1]/preceding::div[1]</value>
      <webElementGuid>d78db03b-8326-47f3-b1c8-4cb6f5c4115c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Photo Attachment'])[2]/preceding::div[1]</value>
      <webElementGuid>05797a83-b528-4380-959e-9e4614752d6c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/div/div/div[2]/div/div</value>
      <webElementGuid>d25b6b1f-24b7-4a16-b143-630f72af6570</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
