<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_to_p-inputtext p-component p-inputnumber-input w-full</name>
   <tag></tag>
   <elementGuidId>6b6c2b59-5d21-4df8-a6a0-69a0fbb402dd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//input[@value='1.00'])[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.p-inputnumber.p-component.p-inputwrapper.p-inputwrapper-filled.p-inputwrapper-focus.ml-2.w-full > input.p-inputtext.p-component.p-inputnumber-input.w-full</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@type = 'text']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9d20b227-463b-4648-88ff-be956a746b00</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>009cc510-ce49-49cc-99f7-d98405dbef46</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>p-inputtext p-component p-inputnumber-input w-full</value>
      <webElementGuid>b29fa100-952e-4d7e-b1f6-7d64d244bbdf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>spinbutton</value>
      <webElementGuid>5f4c4928-6b43-4f01-8d0f-7f720d8b01fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-valuenow</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>ad0ff530-d1ad-477b-a3c4-5e030cea3bea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>inputmode</name>
      <type>Main</type>
      <value>decimal</value>
      <webElementGuid>9afd8ad8-f520-419b-aa84-66db3db336de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-pc-name</name>
      <type>Main</type>
      <value>pcinputtext</value>
      <webElementGuid>2e7a9680-4ae9-47a2-8128-492660707c46</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-pc-extend</name>
      <type>Main</type>
      <value>inputtext</value>
      <webElementGuid>10ac7b94-106d-4a75-bdf4-7161afadbd80</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-pc-section</name>
      <type>Main</type>
      <value>root</value>
      <webElementGuid>5fb53185-98f6-4ce0-9130-13c76c0fc978</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>1.00</value>
      <webElementGuid>ce1fada0-1362-4ff1-bd9d-b4a6489b4ca4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pv_id_19_content&quot;)/div[@class=&quot;p-panel-content&quot;]/div[1]/div[@class=&quot;grid space-y-4&quot;]/div[@class=&quot;col-12 md:col-6&quot;]/div[@class=&quot;field&quot;]/div[@class=&quot;w-full flex align-content-center align-items-center&quot;]/span[@class=&quot;p-inputnumber p-component p-inputwrapper p-inputwrapper-filled p-inputwrapper-focus ml-2 w-full&quot;]/input[@class=&quot;p-inputtext p-component p-inputnumber-input w-full&quot;]</value>
      <webElementGuid>af4e3c85-a5ab-4e90-b744-c4ef696f3e4c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@value='1.00'])[2]</value>
      <webElementGuid>655e3094-dd8d-4c4c-bf89-4cfa83b1381c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='pv_id_19_content']/div/div/div/div/div/div/span[2]/input</value>
      <webElementGuid>de31629b-3be4-4f55-acdf-b59bd662ecb1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[2]/input</value>
      <webElementGuid>4035243a-db58-4c55-8a5c-918102f3ffae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text']</value>
      <webElementGuid>bc925fd9-7f77-4131-a03f-9e8262cede93</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
