<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Green_p-inputtext p-component p-inputnumber-input w-full</name>
   <tag></tag>
   <elementGuidId>15aa1a21-d569-4101-aab6-95249c634ca8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@value='1.00']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.p-inputnumber.p-component.p-inputwrapper.p-inputwrapper-filled.p-inputwrapper-focus.mr-2.w-full > input.p-inputtext.p-component.p-inputnumber-input.w-full</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@value = '1.00']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a6415c5b-b97f-4da5-96c3-aa6cbe86f66a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>62dd58c6-f35e-40e9-92a5-55bfb3780af8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>p-inputtext p-component p-inputnumber-input w-full</value>
      <webElementGuid>0387e42c-0a2f-4410-b8d5-520b3c0bfc56</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>spinbutton</value>
      <webElementGuid>8da23be5-8827-4fc5-8571-133f1549ac9a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-valuenow</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>da393b37-21ef-4955-bc3c-942f0436001f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>inputmode</name>
      <type>Main</type>
      <value>decimal</value>
      <webElementGuid>9a2b2a23-27bc-4757-97fd-3dd5daa324c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-pc-name</name>
      <type>Main</type>
      <value>pcinputtext</value>
      <webElementGuid>266c7cd1-4b78-4fb9-9305-2ac29ff547b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-pc-extend</name>
      <type>Main</type>
      <value>inputtext</value>
      <webElementGuid>ad8863a9-9cac-4c6d-ab20-846c7364cad6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-pc-section</name>
      <type>Main</type>
      <value>root</value>
      <webElementGuid>02ef8d60-f65c-4beb-bc12-757e6b5e5d22</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>1.00</value>
      <webElementGuid>3008ba61-58ca-4159-a201-ae28f31e4034</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pv_id_19_content&quot;)/div[@class=&quot;p-panel-content&quot;]/div[1]/div[@class=&quot;grid space-y-4&quot;]/div[@class=&quot;col-12 md:col-6&quot;]/div[@class=&quot;field&quot;]/div[@class=&quot;w-full flex align-content-center align-items-center&quot;]/span[@class=&quot;p-inputnumber p-component p-inputwrapper p-inputwrapper-filled p-inputwrapper-focus mr-2 w-full&quot;]/input[@class=&quot;p-inputtext p-component p-inputnumber-input w-full&quot;]</value>
      <webElementGuid>156e5d21-c907-42c0-9fb8-ae66f762622c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@value='1.00']</value>
      <webElementGuid>fc119acf-2921-4dbc-b10b-dda7794be2a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='pv_id_19_content']/div/div/div/div/div/div/span/input</value>
      <webElementGuid>6a138ce4-8862-491b-9711-c108ae954c5c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[2]/div/div/div/div/div/div/span/input</value>
      <webElementGuid>0cbe83d2-a5c5-4521-ab4f-d775acc89452</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text']</value>
      <webElementGuid>8cb47e29-9d89-45ef-bf61-46354b127606</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
