<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Reference Photo (for instruction)_p-inputtext p-component mr-2 w-full</name>
   <tag></tag>
   <elementGuidId>1038d56b-89ab-4cd4-9600-c6bc0d6575da</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@type = 'text' and @class = 'p-inputtext p-component mr-2 w-full' and @placeholder = 'Question']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//input[@value=''])[6]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>8b86a5f1-3558-48b5-8d74-b7e9e75a2791</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>bcd7c3ed-78f6-4a4f-8874-174a273071ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>p-inputtext p-component mr-2 w-full</value>
      <webElementGuid>624a4ff3-67fd-4d0a-95e9-28b9193cdf32</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Question</value>
      <webElementGuid>79f63937-5e64-4684-8317-91c668007d2c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-pc-name</name>
      <type>Main</type>
      <value>inputtext</value>
      <webElementGuid>4d8be515-d959-41e0-a305-b419ea97d1a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-pc-section</name>
      <type>Main</type>
      <value>root</value>
      <webElementGuid>aec2902d-70d0-43e7-96f0-c3d270f418f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pv_id_13_content&quot;)/div[@class=&quot;p-panel-content&quot;]/div[1]/div[@class=&quot;p-panel p-component p-panel-toggleable mb-3 cursor-move&quot;]/div[@class=&quot;p-panel-header !bg-slate-100 mb-4&quot;]/div[@class=&quot;flex w-2/3&quot;]/input[@class=&quot;p-inputtext p-component mr-2 w-full&quot;]</value>
      <webElementGuid>a3d8691b-cd25-4b8f-93d1-3be0c028fb94</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@value=''])[6]</value>
      <webElementGuid>e92cef31-e05b-499b-a9c3-e1eb25046b32</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='pv_id_13_content']/div/div/div[3]/div/div/input</value>
      <webElementGuid>7c472754-981a-4947-b04b-0a06ea6cabfd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/input</value>
      <webElementGuid>c78d56c6-7592-4d04-a59d-a065db44d169</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @placeholder = 'Question']</value>
      <webElementGuid>ccf8cafd-2897-43a5-b04a-e101f1ffa871</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
